# Generated by Django 5.0.4 on 2024-05-30 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Register', '0005_alter_embarcacion_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion_Amarra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('cant_dias', models.TextField()),
                ('ubicacion', models.TextField()),
                ('dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register.user')),
            ],
        ),
    ]
