# Generated by Django 5.0.4 on 2024-06-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amarra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion_amarra',
            name='cant_dias',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='publicacion_amarra',
            name='precio',
            field=models.TextField(),
        ),
    ]
