# Generated by Django 5.0.4 on 2024-06-01 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amarra', '0002_alter_publicacion_amarra_cant_dias_and_more'),
        ('Register', '0005_alter_embarcacion_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(null=True)),
                ('cant_dias', models.TextField()),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Amarra.publicacion_amarra')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register.user')),
            ],
        ),
    ]
