# Generated by Django 5.0.4 on 2024-06-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amarra', '0005_alter_publicacion_amarra_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion_amarra',
            name='cant_dias_disponibles',
            field=models.IntegerField(default=0),
        ),
    ]
