# Generated by Django 5.0.4 on 2024-06-07 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amarra', '0005_alter_publicacion_amarra_estado'),
        ('Register', '0005_alter_embarcacion_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion_amarra',
            name='cant_dias_disponibles',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='publicacion_amarra',
            name='dueño',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Register.user'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('Vigente', 'Vigente'), ('En Proceso', 'En Proceso'), ('Finalizado', 'Finalizado')], default='Vigente', max_length=20),
        ),
    ]
