# Generated by Django 5.0.4 on 2024-05-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='estado_cuenta',
            field=models.CharField(choices=[('Habilitado', 'Habilitado'), ('Deshabilitado', 'Deshabilitado')], default='Deshabilitado', max_length=20),
        ),
    ]
