# Generated by Django 5.0.4 on 2024-05-11 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='datos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Register.usuario'),
        ),
    ]
