# Generated by Django 5.0.4 on 2024-05-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0002_alter_user_estado_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embarcacion',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
