# Generated by Django 5.0.4 on 2024-05-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0003_alter_embarcacion_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='moroso',
            field=models.BooleanField(default=False),
        ),
    ]
