# Generated by Django 5.0.4 on 2024-05-13 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0002_alter_user_estado_cuenta'),
        ('Trueque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion_embarcacion',
            name='embarcacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register.embarcacion'),
        ),
        migrations.AlterField(
            model_name='publicacion_embarcacion',
            name='estado',
            field=models.CharField(max_length=50),
        ),
    ]
