# Generated by Django 5.0.4 on 2024-05-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trueque', '0002_alter_publicacion_embarcacion_embarcacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion_objetovalioso',
            name='foto',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
