# Generated by Django 5.0.4 on 2024-05-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trueque', '0003_alter_publicacion_objetovalioso_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion_objetovalioso',
            name='foto',
            field=models.ImageField(upload_to='img_pu/'),
        ),
    ]
