# Generated by Django 5.0.4 on 2024-05-15 02:52

import django.db.models.deletion
from django.db import migrations, models
from Register.models import User


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0003_alter_embarcacion_foto'),
        ('Trueque', '0005_solicitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud_Embarcaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trueque.publicacion_embarcacion')),
                ('usuario_interesado',models.ForeignKey(null=True, on_delete=models.SET_NULL, to='Register.User')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud_ObjetosValiosos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trueque.publicacion_objetovalioso')),
                ('usuario_interesado', models.ForeignKey(null=True, on_delete=models.SET_NULL, to='Register.User')),
            ],
        ),
        migrations.DeleteModel(
            name='Solicitud',
        ),
    ]
