# Generated by Django 5.0.4 on 2024-05-15 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0003_alter_embarcacion_foto'),
        ('Trueque', '0005_solicitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud_Embarcaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trueque.publicacion_embarcacion')),
                ('usuarios_interesados', models.ManyToManyField(related_name='solicitudes_embarcaciones', to='Register.user')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud_ObjetosValiosos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trueque.publicacion_objetovalioso')),
                ('usuarios_interesados', models.ManyToManyField(related_name='solicitudes_objetos_valiosos', to='Register.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Solicitud',
        ),
    ]
