# Generated by Django 5.0.4 on 2024-05-15 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trueque', '0006_solicitud_embarcaciones_solicitud_objetosvaliosos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeSolicitudEmbarcaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('solicitud_embarcacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trueque.solicitud_embarcaciones')),
            ],
        ),
        migrations.CreateModel(
            name='MensajeSolicitudObjetosValiosos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('solicitud_objeto_valioso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trueque.solicitud_objetosvaliosos')),
            ],
        ),
    ]
