# Generated by Django 5.0.4 on 2024-05-22 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0003_alter_embarcacion_foto'),
        ('Trueque', '0007_mensajesolicitudembarcaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_embarcaciones',
            name='iniciado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitud_objetosvaliosos',
            name='iniciado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='solicitud_embarcaciones',
            name='usuario_interesado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_embarcaciones', to='Register.user'),
        ),
        migrations.AlterField(
            model_name='solicitud_objetosvaliosos',
            name='usuario_interesado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_objetos_valiosos', to='Register.user'),
        ),
    ]
