# Generated by Django 5.0.4 on 2024-05-23 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0004_user_moroso'),
        ('Trueque', '0010_remove_message_conversation_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajes_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje_texto', models.TextField()),
                ('enviado_a', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trueque.conversacion')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Mesajes_chat',
        ),
    ]
