# Generated by Django 5.0.4 on 2024-06-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trueque', '0011_mensajes_chat_delete_mesajes_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion_objetovalioso',
            name='foto',
            field=models.ImageField(upload_to='static/img_o/'),
        ),
    ]
