# Generated by Django 5.0.4 on 2024-06-20 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0005_alter_embarcacion_foto'),
        ('Trueque', '0012_alter_publicacion_objetovalioso_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje_texto', models.TextField()),
                ('denunciado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias_recibidas', to='Register.user')),
                ('denunciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias_realizadas', to='Register.user')),
            ],
            options={
                'unique_together': {('denunciado', 'denunciante')},
            },
        ),
    ]
