# Generated by Django 5.0.4 on 2024-06-20 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0005_alter_embarcacion_foto'),
        ('Trueque', '0013_denuncia'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='denuncia',
            unique_together={('denunciado', 'denunciante', 'mensaje_texto')},
        ),
    ]
