# Generated by Django 5.0.4 on 2024-07-02 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trueque', '0014_alter_denuncia_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='mensaje',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mensaje', to='Trueque.mensajes_chat'),
        ),
    ]
