# Generated by Django 5.0.4 on 2024-07-05 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Amarra', '0006_alter_publicacion_amarra_cant_dias_disponibles_and_more'),
        ('Register', '0005_alter_embarcacion_foto'),
        ('Trueque', '0014_alter_denuncia_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valoracion_Amarra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrellas', models.IntegerField()),
                ('comentario', models.TextField()),
                ('estado', models.CharField(choices=[('Inicio', 'Inicio'), ('Proceso', 'Proceso'), ('Finalizado', 'Finalizado')], max_length=50)),
                ('respuesta', models.TextField()),
                ('dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_amarra', to='Register.user')),
                ('publicacion_amarra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Amarra.publicacion_amarra')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Register.user')),
            ],
        ),
        migrations.CreateModel(
            name='Valoracion_Trueque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_publicacion', models.CharField(choices=[('ObjetoValioso', 'Objeto Valioso'), ('Embarcacion', 'Embarcación')], max_length=20)),
                ('estrellas', models.IntegerField()),
                ('comentario', models.TextField()),
                ('estado', models.CharField(choices=[('Inicio', 'Inicio'), ('Proceso', 'Proceso'), ('Finalizado', 'Finalizado')], max_length=50)),
                ('respuesta', models.TextField()),
                ('dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_trueque', to='Register.user')),
                ('publicacion_embarcacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Trueque.publicacion_embarcacion')),
                ('publicacion_objeto_valioso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Trueque.publicacion_objetovalioso')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Register.user')),
            ],
        ),
    ]
