# Generated by Django 5.0.4 on 2024-07-06 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0005_alter_embarcacion_foto'),
        ('Valoracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Espera', 'Espera'), ('Respondido', 'Respondido')], default='Pendiente', max_length=20)),
                ('mensaje_texto', models.TextField()),
                ('mostrar', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register.user')),
                ('valoracion_amarra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='Valoracion.valoracion_amarra')),
                ('valoracion_trueque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='Valoracion.valoracion_trueque')),
            ],
        ),
        migrations.CreateModel(
            name='ValoracionAmarraOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio_estrellas', models.IntegerField(default=0, help_text='Promedio de valoración recibida de amarras (0-5)')),
                ('dueño', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_amarra_owner', to='Register.user')),
            ],
        ),
        migrations.CreateModel(
            name='ValoracionObjetoValiosoOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio_estrellas', models.IntegerField(default=0, help_text='Promedio de valoración recibida de objetos valiosos (0-5)')),
                ('dueño', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_objeto_valioso_owner', to='Register.user')),
            ],
        ),
        migrations.CreateModel(
            name='ValoracionTruequeOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio_estrellas', models.IntegerField(default=0, help_text='Promedio de valoración recibida de trueques (0-5)')),
                ('dueño', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_trueque_owner', to='Register.user')),
            ],
        ),
    ]
